### ISSUE TITLE
Mix uprate/downrate support negative range

### ISSUE THREAD

**Issue by x0urc3** [yschaeff/HK-T6Av2#2]
The mixer uprate/downrate weight support negative value. This is useful for various application i.e. plane flaperon. Attached patch should fix this.

[mix_range_patch.txt](https://github.com/yschaeff/HK-T6Av2/files/916373/mix_range_patch.txt)

**Comment by yschaeff** [comment]
Hi, thank you for your contribution. I have not tested it (likely won't any time soon) but I did apply your patch. Happy to see somebody picked up my work. :)

**Comment by kmbs2002** [comment]
Great. Thanks for providing an alternative software to configure my rc remote
